### PR TITLE
chart component with full table view, release tags, optimizations

### PR DESCRIPTION
**Pull request by mrabans**

### CODE REVIEW

**Comment by mrabans** [comment]
@Piiit you have to override your modifications on development branch

**Comment by Piiit** [comment]
> @Piiit you have to override your modifications on development branch

@mrabans Which modifications? I just merged the other PRs...  The problem here is that you branched from main, but send a PR to the development branch, please in the future branch or rebase directly from development.

Normally the workflow is as follows:
- Contributors open a PR
- Contributors resolve conflicts (if this involves overriding changes, put them into the PR)
- Contributors resolve other issues mentioned in the CI logs (if possible, otherwise this is a work for NOI)
- NOI merges to development

If you need help with the rebasing or any other things, please let me know.

Thanks for the PR :-)

**Review by Piiit — CHANGES_REQUESTED** [review]
See comment in main section

**Comment by mrabans** [comment]
All resolved in https://github.com/noi-techpark/aliens4friends-dashboard/pull/19

**Pull request closed without merging**
