### PR TITLE
chart component with full table view, release tags, optimizations (#2)

### PR DESCRIPTION
**Pull request by mrabans**

### CODE REVIEW

**Comment by Piiit** [comment]
@mrabans The CI fails, please have  a look at the output --> https://ci.opendatahub.bz.it/job/eu.testingmachine.solda.dashboard/job/PR-16/1/console

**Review by Piiit — CHANGES_REQUESTED** [review]
See main comment... CI fails

**Comment by mrabans** [comment]
I'll have a look

**Comment by mrabans** [comment]
Please see https://github.com/noi-techpark/aliens4friends-dashboard/pull/18 and close this one

**Comment by mrabans** [comment]
All resolved in https://github.com/noi-techpark/aliens4friends-dashboard/pull/19

**Pull request closed without merging**
