### PR TITLE
prevent container .env override

### PR DESCRIPTION
**Pull request by mrabans**

### CODE REVIEW

**Comment by Piiit** [comment]
@mrabans @ag0n-e Thx, but we need the .env files to deploy it also on different machines... I understand the issue now, and try to solve it with a .env file...

**Comment by Piiit** [comment]
@ag0n-e I will write you, thanks... this problem has nothing to do with Jenkins thou

**Comment by Piiit** [comment]
This has been fixed by cherry-picking relevant parts...

**Comment by mrabans** [comment]
@Piiit alright, so we update our next dev branch from noi-techpark:development, or do you have further plans for merging into main or similar?

**Comment by Piiit** [comment]
@mrabans Hi, it is always the development branch... please see https://github.com/noi-techpark/odh-docs/wiki/Contributor-Guidelines:-Getting-started and https://docs.opendatahub.bz.it/en/latest/guidelines/contributors.html

**Pull request closed without merging**
